baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  teaching: "/teaching/:year/:month/:day/:slug/"
  publications: "/publications/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Publications
      url: "publications/"
      weight: 2
    - name: Teaching
      url: "teaching/"
      weight: 3


params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Jose Toledo] 2022 | [Github](https://github.com/toledo60) | [ORCID](https://orcid.org/0000-0001-8559-0027)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
